// THIS FILE IS AUTOGENERATED BY GRAPHQL-CODEGEN. DO NOT EDIT!

export interface PossibleTypesResultData {
	possibleTypes: {
		[key: string]: string[]
	}
}

const result: PossibleTypesResultData = {
	'possibleTypes': {
		'Node': [
			'File',
			'Folder',
		],
	},
};
export default result;
